[lock]
version = "2"
hub = "https://hub.bend-lang.com"
[tools]
[tools.bolt]
git = "https://github.com/Emerging-Patterns/bolt"
rev = "d08744eccf71fda5cc2132fd9fbd733a08b83cb1"
tag = "v1.12.0"
root = "."
narHash = "sha256-WxS7HW29rbO5JKFCdEM7uIdZ1Dn43zj8/3N1h/xMWGo="
entry = "main.bend"
