name: publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing tag to publish, e.g. v0.4.0"
        required: true
        type: string

jobs:
  publish:
    uses: Emerging-Patterns/actions/.github/workflows/publish.yml@9523e8b294ae014fade5861c32d5ab911866acb2
    with:
      tag: ${{ inputs.tag }}
