name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    permissions:
      contents: write
    uses: Emerging-Patterns/actions/.github/workflows/github-release.yml@9523e8b294ae014fade5861c32d5ab911866acb2
